name: H3-Pipeline-Analysis

on:
  push:
    branches:
      - main

jobs:
  call-local-api:
    runs-on: ubuntu-latest

    steps:
      - name: Make API call to local server
        run: |
          # Use curl to call the API endpoint, for example:
          curl -X POST "https://c93a-195-252-220-98.ngrok-free.app/api/git/analyze_repo" -H "Content-Type: application/json" -d '{"repo_id": "$2a$10$gcKiez4C5NBQ1cdrUR9Ve.OBYj/ZD7zNO1c5hv57hjLJD.tGlaVHK"}'
